services:
  # Backend API Service
  - type: web
    name: cyberspace-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://cyberspace-frontend.onrender.com
      - key: CORS_ORIGIN
        value: https://cyberspace-frontend.onrender.com
      - key: LOG_LEVEL
        value: info

  # Frontend Static Site
  - type: web
    name: cyberspace-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: .
    envVars:
      - key: VITE_BACKEND_URL
        value: https://cyberspace-backend.onrender.com
      - key: VITE_EXTENSION_DOWNLOAD_URL
        value: https://cyberspace-frontend.onrender.com/extension.crx
