services:
  - type: web
    name: cyberspace-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://cyberspace-backend.onrender.com
